In [5]:
import numpy as np
import pandas as pd

In [33]:
df=pd.DataFrame({"Marks":[20,30,None,40,None]})
df

   Marks
0   20.0
1   30.0
2    NaN
3   40.0
4    NaN

In [47]:
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
df

   Marks
0   20.0
1   30.0
2   30.0
3   40.0
4   30.0

In [59]:
ndf=pd.DataFrame({"Score":[10,30,None,15,None]})
ndf

   Score
0   10.0
1   30.0
2    NaN
3   15.0
4    NaN

In [61]:
ndf["Score"]=ndf["Score"].fillna(ndf["Score"].median())
ndf

   Score
0   10.0
1   30.0
2   15.0
3   15.0
4   15.0

In [83]:
a=pd.DataFrame({"RUN":[20,10,None,10,15,None]})
a

    RUN
0  20.0
1  10.0
2   NaN
3  10.0
4  15.0
5   NaN

In [85]:
a["RUN"]=a["RUN"].fillna(a["RUN"].mode()[0])
a

    RUN
0  20.0
1  10.0
2  10.0
3  10.0
4  15.0
5  10.0

In [87]:
b=pd.DataFrame({"NAME":["ishika","puja",None,"puja","piku",None]})
b

     NAME
0  ishika
1    puja
2    None
3    puja
4    piku
5    None

In [93]:
b["NAME"]=b["NAME"].fillna(b["NAME"].mode()[0])
b

     NAME
0  ishika
1    puja
2    puja
3    puja
4    piku
5    puja