In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('data.csv')
df

     Name  Roll  Marks      Add
0  ishika   101    NaN   ghatal
1     NaN   102  325.0   daspur
2   dipti   103  412.0  chaipat
3    debu   104  278.0      NaN
4     NaN   105  564.0  kolkata
5    piku   106  297.0   daspur
6     ani   107    NaN   ghatal
7  dipali   108  459.0    debra
8   koyel   109  657.0      NaN
9     NaN   110  354.0    debra

In [8]:
print(df.isna().sum())

Name     3
Roll     0
Marks    2
Add      2
dtype: int64

In [44]:
n_df=df['Marks'].fillna(df['Marks'].mean())
n_df

0    418.25
1    325.00
2    412.00
3    278.00
4    564.00
5    297.00
6    418.25
7    459.00
8    657.00
9    354.00
Name: Marks, dtype: float64

In [42]:
n_df=df.fillna(method='bfill')
n_df

C:\Users\BCA LAB 10\AppData\Local\Temp\ipykernel_7156\3609199973.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  n_df=df.fillna(method='bfill')

     Name  Roll  Marks      Add
0  ishika   101  325.0   ghatal
1   dipti   102  325.0   daspur
2   dipti   103  412.0  chaipat
3    debu   104  278.0  kolkata
4    piku   105  564.0  kolkata
5    piku   106  297.0   daspur
6     ani   107  459.0   ghatal
7  dipali   108  459.0    debra
8   koyel   109  657.0    debra
9     NaN   110  354.0    debra